// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIReblupPcQAvrXwwaUIdjaya_G2B3ofU',
    appId: '1:837167400681:web:1c1702f015f8d31ae65278',
    messagingSenderId: '837167400681',
    projectId: 'beatz-ca93c',
    authDomain: 'beatz-ca93c.firebaseapp.com',
    storageBucket: 'beatz-ca93c.appspot.com',
    measurementId: 'G-L1W9HYGXKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJouBycdvvoT2Bd-caWwiVXdfpLlnORnA',
    appId: '1:837167400681:android:24bad0d8e52fdd63e65278',
    messagingSenderId: '837167400681',
    projectId: 'beatz-ca93c',
    storageBucket: 'beatz-ca93c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC169eXWWP5f17Vr-BfJGG919aQs7hbQwc',
    appId: '1:837167400681:ios:01d73af0494a859be65278',
    messagingSenderId: '837167400681',
    projectId: 'beatz-ca93c',
    storageBucket: 'beatz-ca93c.appspot.com',
    iosBundleId: 'com.example.beatzMusicplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC169eXWWP5f17Vr-BfJGG919aQs7hbQwc',
    appId: '1:837167400681:ios:01d73af0494a859be65278',
    messagingSenderId: '837167400681',
    projectId: 'beatz-ca93c',
    storageBucket: 'beatz-ca93c.appspot.com',
    iosBundleId: 'com.example.beatzMusicplayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIReblupPcQAvrXwwaUIdjaya_G2B3ofU',
    appId: '1:837167400681:web:790a6eb220f77cb5e65278',
    messagingSenderId: '837167400681',
    projectId: 'beatz-ca93c',
    authDomain: 'beatz-ca93c.firebaseapp.com',
    storageBucket: 'beatz-ca93c.appspot.com',
    measurementId: 'G-D0TBPTF8EE',
  );

}